"""
Django settings for gtm_validator project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-c=&nz9k*2q%_@ft=n_+ut(uz=!wgql1sxyo!q9qnrz@bx05=1y")

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True for local dev safety; explicitly set DEBUG=False in production
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,forge.funti3r.xyz,gtm-validator-601175512678.us-west1.run.app").split(",")

# Error tracking (optional -- only active when SENTRY_DSN is set; safe to
# leave sentry-sdk installed with no DSN configured, e.g. local dev/CI).
# Initialized early since this is otherwise zero-effort/zero-code-elsewhere:
# DjangoIntegration auto-enables once sentry_sdk.init() runs in a process
# where django is importable, no explicit integration wiring needed.
SENTRY_DSN = os.getenv("SENTRY_DSN", "").strip()
if SENTRY_DSN:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.getenv("ENVIRONMENT", "development"),
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1")),
        send_default_pii=False,
    )

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    # Apps
    "gtm",  
    "dashboard",
    "theme",
    
    # Django-tailwind - commented out until installed
    # 'tailwind',
    
    # allauth
    'allauth',
    'allauth.account',
    
    # htmx
    'django_htmx',
    
    # Turbo
    'turbo_response',
]

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1"
]

# NPM_BIN_PATH only needed for local Tailwind development
NPM_BIN_PATH = os.getenv("NPM_BIN_PATH", r"C:\Program Files\nodejs\npm.cmd")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "gtm.middleware.EnsureClientIdMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # Must come after AuthenticationMiddleware (needs request.user) and
    # MessageMiddleware (uses messages.error on the non-member redirect path).
    "gtm.middleware_workspace.WorkspaceMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

MIDDLEWARE.append("allauth.account.middleware.AccountMiddleware")

ROOT_URLCONF = "gtm_validator.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Project-level dir is searched before app dirs, so admin template
        # overrides here win over django.contrib.admin's (which is listed
        # earlier in INSTALLED_APPS).
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "gtm.context_processors.workspace_permissions",
            ],
        },
    },
]

WSGI_APPLICATION = "gtm_validator.wsgi.application"

# Use cookie-based sessions for Cloud Run scalability
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
SESSION_COOKIE_HTTPONLY = True

# Database configuration - dynamically choose based on environment
if os.getenv("ENVIRONMENT") == "production" or os.getenv("DATABASE_URL"):
    # Production: Use PostgreSQL via Cloud SQL
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "gtm_validator",
            "USER": "gtm_user",
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": "/cloudsql/forge-497716:us-west1:gtm-db-v2",
            "PORT": "",
            "CONN_MAX_AGE": 60,
            "CONN_HEALTH_CHECKS": True,
        }
    }
else:
    # Development: Use SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Modern Django 4.2+ / 5.x configuration for WhiteNoise static storage
GS_BUCKET_NAME = os.getenv("GCS_BUCKET_NAME", "")
# Evidence documents are business-confidential, so the bucket stays private
# and access happens via short-lived signed URLs. Cloud Run has no service
# account key file to sign with directly, so signing goes through the IAM
# Credentials API (signBlob) against the attached service account instead.
# GS_IAM_SIGN_BLOB requires django-storages >= 1.14.6; GS_SA_EMAIL tells the
# signBlob call which service account to sign as (the one Cloud Run runs as).
GS_DEFAULT_ACL = None
GS_QUERYSTRING_AUTH = True
GS_IAM_SIGN_BLOB = True
GS_SA_EMAIL = os.getenv(
    "GS_SA_EMAIL", "forge-177@forge-497716.iam.gserviceaccount.com"
)
GS_EXPIRATION = 3600  # signed URL lifetime, seconds

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
    } if GS_BUCKET_NAME else {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Media files (Uploads) - served from Cloud Storage in production when
# GCS_BUCKET_NAME is set; falls back to local disk for local dev.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email Configuration
if DEBUG or os.getenv("EMAIL_CONSOLE", "").lower() == "true":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

# Brand shown in emails (subjects, headers, footers). Central so a rename is
# one edit rather than scattered string literals across templates/helpers.
BRAND_NAME = "ForgeGTM"

# Absolute base URL for links in emails sent without a request object
# (notifications, snapshot reports). Must be the real public URL in prod --
# the old localhost fallback produced dead links. Override via env when the
# custom domain lands.
SITE_BASE_URL = os.getenv(
    "SITE_BASE_URL", "https://gtm-validator-601175512678.us-west1.run.app"
)
BRAND_URL = os.getenv("BRAND_URL", SITE_BASE_URL)

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    f"{BRAND_NAME} <{os.getenv('EMAIL_HOST_USER', 'noreply@funti3r.xyz')}>"
)
SERVER_EMAIL = os.getenv("SERVER_EMAIL", os.getenv("EMAIL_HOST_USER", "noreply@funti3r.xyz"))
EMAIL_SUBJECT_PREFIX = f"[{BRAND_NAME}] "

GTM_REPORT_INTERNAL_TO = ["gtm-reports@funti3r.xyz"]
EMAIL_REDIRECT_TO = os.getenv("EMAIL_REDIRECT_TO", "").strip()

# Beta cost/access safety net (see gtm/ai_credits.py, gtm/views_workspace.py).
# AI_GLOBAL_DAILY_TOKEN_CAP unset/0 = no global ceiling (opt-in, so existing
# single-tenant usage doesn't suddenly start failing).
AI_GLOBAL_DAILY_TOKEN_CAP = int(os.getenv("AI_GLOBAL_DAILY_TOKEN_CAP", "0") or 0)
BETA_ALERT_EMAIL = os.getenv("BETA_ALERT_EMAIL", "").strip()
MAX_WORKSPACES_PER_USER = int(os.getenv("MAX_WORKSPACES_PER_USER", "1") or 1)

# Zero-new-dependency fallback for unhandled 500s: Django's own
# AdminEmailHandler is already attached to the "django" logger by
# DEFAULT_LOGGING (confirmed -- our custom LOGGING dict below doesn't
# override the "django" logger, and disable_existing_loggers=False leaves
# it in place); it only actually sends anything once ADMINS is non-empty
# and DEBUG=False (AdminEmailHandler's own require_debug_false filter).
# Reuses BETA_ALERT_EMAIL rather than a separate setting -- one place to
# configure "who hears about beta problems."
if BETA_ALERT_EMAIL:
    ADMINS = [("Beta Alerts", BETA_ALERT_EMAIL)]
    MANAGERS = ADMINS

GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID", "")
GCP_LOCATION = os.getenv("GCP_LOCATION", "us-central1")
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "")

if GOOGLE_APPLICATION_CREDENTIALS and not os.environ.get("GOOGLE_APPLICATION_CREDENTIALS"):
    creds_path = BASE_DIR / GOOGLE_APPLICATION_CREDENTIALS if not GOOGLE_APPLICATION_CREDENTIALS.startswith("/") else GOOGLE_APPLICATION_CREDENTIALS
    if creds_path.exists():
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(creds_path)

# Auto-read project ID from service account JSON if env var is missing or still the placeholder
if not GCP_PROJECT_ID or GCP_PROJECT_ID == "your-gcp-project-id":
    _creds_file = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "")
    if _creds_file:
        try:
            import json as _json
            with open(_creds_file) as _f:
                _sa = _json.load(_f)
            GCP_PROJECT_ID = _sa.get("project_id", "") or GCP_PROJECT_ID
        except Exception:
            pass

# Encryption key for workspace-integration credentials (e.g. HubSpot tokens) at rest.
# A dedicated key (not derived from SECRET_KEY unconditionally) so that rotating
# SECRET_KEY for a security incident doesn't also corrupt every stored integration
# token as a side effect -- SECRET_KEY also signs sessions/CSRF (signed_cookies).
# Falls back to a key derived from SECRET_KEY for local dev convenience, matching
# this project's existing "insecure default for dev" pattern; set an explicit,
# independently-rotatable INTEGRATION_ENCRYPTION_KEY in production.
INTEGRATION_ENCRYPTION_KEY = os.getenv("INTEGRATION_ENCRYPTION_KEY", "")
if not INTEGRATION_ENCRYPTION_KEY:
    import base64 as _base64
    import hashlib as _hashlib
    INTEGRATION_ENCRYPTION_KEY = _base64.urlsafe_b64encode(
        _hashlib.sha256(SECRET_KEY.encode("utf-8")).digest()
    ).decode("utf-8")

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = 'gtm:landing'
LOGOUT_REDIRECT_URL = 'gtm:landing'
ACCOUNT_LOGOUT_REDIRECT_URL = 'gtm:landing'
# Closed-beta gate: adds a required invite-code field to allauth's stock
# signup form (see gtm/forms_beta.py). Remove this line to reopen public
# signup once the beta is over.
ACCOUNT_SIGNUP_FORM_CLASS = 'gtm.forms_beta.BetaInviteSignupForm'

# CSRF validation handled via standard token validation for same-origin requests
CSRF_TRUSTED_ORIGINS = [
    "https://forge.funti3r.xyz",
    "https://gtm-validator-601175512678.us-west1.run.app",
    "http://localhost:8000",
]

# HTTPS security headers applied automatically when DEBUG is off
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Cloud-safe Logging: File Handler removed to prevent container environment write crashes.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(asctime)s [%(levelname)s] %(message)s"},
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "gtm": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.security.csrf": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}