# Generated by Django 5.2.7 on 2025-10-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsession",
            name="current_step",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
