# Generated by Django 5.2.7 on 2025-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm", "0002_assessmentsession_current_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsession",
            name="owner_client_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
