# Generated by Django 5.2.7 on 2025-10-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm", "0004_actionitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("tools", models.TextField(help_text="Comma-separated list of tools")),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gtm.category"
                    ),
                ),
            ],
        ),
    ]
