# Generated by Django 5.2.7 on 2025-10-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm", "0006_resultsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsession",
            name="company_size",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="contact_role",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="country",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="crm",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="referrer",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="revenue_range",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="utm_campaign",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="utm_medium",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="utm_source",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="assessmentsession",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="assessmentsession",
            name="current_step",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="assessmentsession",
            name="industry",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="assessmentsession",
            name="owner_client_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
