# Generated by Django 5.2.7 on 2025-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm", "0007_assessmentsession_company_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultsnapshot",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="company_size",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="contact_role",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="country",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="crm",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="industry",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="referrer",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="revenue_range",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="utm_campaign",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="utm_medium",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="utm_source",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="resultsnapshot",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
    ]
