# Generated by Django 5.2.7 on 2025-10-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm", "0008_resultsnapshot_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultsnapshot",
            name="report_sent",
            field=models.BooleanField(default=False),
        ),
    ]
