# Generated by Django 5.2.7 on 2025-10-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm", "0009_resultsnapshot_report_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultsnapshot",
            name="ai_playbook",
            field=models.TextField(blank=True, default=""),
        ),
    ]
