# Generated by Django 5.2.7 on 2025-12-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0013_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
