# Generated by Django 5.2.7 on 2025-12-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0014_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='context_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
