# Generated by Django 5.2.7 on 2025-12-09 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0015_response_context_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='gtm.assessmentsession'),
        ),
    ]
