# Generated by Django 5.2.7 on 2025-12-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0016_actionitem_session_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
