# Generated by Django 5.2.7 on 2026-02-11 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0017_actionitem_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Team member assigned to this action item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_action_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company/Organization name', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('company_size', models.CharField(blank=True, max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funti3r_consultant', models.ForeignKey(blank=True, help_text='Funti3r team member managing this workspace', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultancy_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='actionitem',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this action item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='gtm.workspace'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this assessment belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='gtm.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Workspace Admin'), ('manager', 'Manager'), ('contributor', 'Contributor'), ('viewer', 'Viewer'), ('funti3r_consultant', 'Funti3r Consultant')], max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtm.workspace')),
            ],
            options={
                'ordering': ['-invited_at'],
                'unique_together': {('workspace', 'email')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Workspace Admin'), ('manager', 'Manager'), ('contributor', 'Contributor'), ('viewer', 'Viewer'), ('funti3r_consultant', 'Funti3r Consultant')], max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtm.workspace')),
            ],
            options={
                'ordering': ['-invited_at'],
                'unique_together': {('user', 'workspace')},
            },
        ),
    ]
