# Generated by Django 5.2.7 on 2026-02-11 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0018_actionitem_assigned_to_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this action item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_action_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
