# Generated by Django 5.2.7 on 2026-03-14 09:25

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0021_workspaceactivityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
