# Generated by Django 5.2.7 on 2026-03-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0022_question_ai_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceactivityevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_activity_events', to='gtm.assessmentsession'),
        ),
    ]
