# Generated by Django 5.2.7 on 2026-03-20 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0025_chatmessage_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free / Lead'), ('pro', 'Professional'), ('business', 'Business / Agency')], default='free', max_length=20)),
                ('ai_credits', models.IntegerField(default=1, help_text='Number of AI assessment runs allowed')),
                ('is_simulated_pro', models.BooleanField(default=False, help_text='Manual override to simulate Pro access')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
