# Generated by Django 5.2.7 on 2026-03-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0026_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultsnapshot',
            name='ai_risk_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
