# Generated by Django 5.2.7 on 2026-04-04 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0027_actionitem_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTMFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to='gtm/evidence/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('landing_page', 'Landing Page Screenshot'), ('ad_creative', 'Ad Creative Asset'), ('sales_deck', 'Sales Deck / Strategy PDF'), ('other', 'Other Strategic Evidence')], default='other', max_length=40)),
                ('ai_audit_notes', models.TextField(blank=True, default='', help_text="The AI Auditor's critique of this visual/document asset.")),
                ('ai_audit_score_modifier', models.IntegerField(default=0, help_text='Suggested impact on the GTM score (-5 to +5) based on evidence.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='gtm.assessmentsession')),
            ],
            options={
                'verbose_name': 'GTM Strategic Evidence',
                'verbose_name_plural': 'GTM Strategic Evidence',
                'ordering': ['-created_at'],
            },
        ),
    ]
