# Generated by Django 5.2.7 on 2026-04-05 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0028_gtmfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtmfile',
            name='audit_status',
            field=models.CharField(choices=[('none', 'Not Audited'), ('pending', 'Awaiting Audit'), ('auditing', 'Auditing…'), ('complete', 'Audit Complete'), ('failed', 'Audit Failed')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='gtmfile',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Optional: workspace-level evidence (used by the Asset Library)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gtm_files', to='gtm.workspace'),
        ),
        migrations.AlterField(
            model_name='gtmfile',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='gtm.assessmentsession'),
        ),
    ]
