# Generated by Django 5.2.7 on 2026-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0029_gtmfile_audit_status_gtmfile_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='ai_insight_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='resultsnapshot',
            name='ai_playbook_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12),
        ),
    ]
