# Generated by Django 5.2.7 on 2026-05-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0030_add_ai_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsnapshot',
            name='ai_competitor_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resultsnapshot',
            name='ai_financial_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
