# Generated by Django 5.2.7 on 2026-06-25 18:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0032_add_deliverydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_option_labels',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='question',
            name='input_options',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(blank=True, default='scale', max_length=50),
        ),
    ]
