# Generated by Django 5.2.7 on 2026-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0032_add_deliverydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_option_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='input_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
