# Generated by Django 5.2.7 on 2026-06-26 11:04

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0033_question_input_option_labels_question_input_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('demand', 'Demand'), ('conversion', 'Conversion')], max_length=20)),
                ('file', models.FileField(max_length=255, upload_to='gtm/category/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(choices=[('csv', 'CSV Spreadsheet'), ('xlsx', 'Excel Spreadsheet'), ('pdf', 'PDF Document'), ('docx', 'Word Document'), ('txt', 'Text / Notepad File'), ('json', 'JSON Data'), ('image', 'Image / Screenshot'), ('other', 'Other')], default='other', max_length=10)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('analysis_result', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('analysis_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('complete', 'Analysis Complete'), ('failed', 'Analysis Failed')], default='uploaded', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_docs', to='gtm.assessmentsession')),
            ],
            options={
                'verbose_name': 'Category Evidence Document',
                'verbose_name_plural': 'Category Evidence Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
