# Generated by Django 5.2.7 on 2026-07-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0034_add_category_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='company_stage',
            field=models.CharField(blank=True, choices=[('idea', 'Idea / Pre-launch'), ('pre_revenue', 'Early Stage / Pre-Revenue'), ('early_revenue', 'Early Revenue'), ('growth', 'Growth'), ('scale', 'Scale / Mature')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resultsnapshot',
            name='company_stage',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
