# Generated by Django 5.2.7 on 2026-07-11 16:19

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0035_assessmentsession_company_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScoringExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id_code', models.CharField(db_index=True, max_length=10)),
                ('evidence_embedding', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('score', models.PositiveSmallIntegerField()),
                ('confidence', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
