# Generated by Django 5.2.7 on 2026-07-12 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0036_aiscoringexample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('portfolio', 'Portfolio Agent'), ('resource', 'Resource Agent'), ('insights', 'Insights Agent')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_agent_chat_messages', to='gtm.assessmentsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_chat_messages', to='gtm.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workspace', 'agent_type', '-created_at'], name='gtm_workspa_workspa_92ceae_idx')],
            },
        ),
    ]
