# Generated by Django 5.2.7 on 2026-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0037_workspacechatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceactivityevent',
            name='event_type',
            field=models.CharField(choices=[('task_created', 'Task created'), ('task_moved', 'Task moved'), ('task_deleted', 'Task deleted'), ('comment_added', 'Comment added'), ('comment_deleted', 'Comment deleted'), ('resource_created', 'Resource created'), ('resource_updated', 'Resource updated'), ('resource_deleted', 'Resource deleted'), ('client_summary_generated', 'Client summary generated')], max_length=32),
        ),
    ]
