# Generated by Django 5.2.7 on 2026-07-12 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0038_alter_workspaceactivityevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('gtm_strategist', 'GTM Strategist'), ('portfolio', 'Portfolio Agent'), ('resource', 'Resource Agent'), ('insights', 'Insights Agent')], max_length=20)),
                ('doc_type', models.CharField(choices=[('client_summary', 'Client Summary'), ('action_plan', 'Action Plan'), ('roadmap', 'Roadmap'), ('resource_brief', 'Resource Brief'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_documents', to='gtm.assessmentsession')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_documents', to='gtm.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
