# Generated by Django 5.2.7 on 2026-07-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0039_agentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='deliverable_document',
            field=models.ForeignKey(blank=True, help_text='The concrete artifact an AI agent produced to complete this task, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_action_items', to='gtm.agentdocument'),
        ),
        migrations.AlterField(
            model_name='agentdocument',
            name='doc_type',
            field=models.CharField(choices=[('client_summary', 'Client Summary'), ('action_plan', 'Action Plan'), ('roadmap', 'Roadmap'), ('resource_brief', 'Resource Brief'), ('action_item_deliverable', 'Action Item Deliverable'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
