# Generated by Django 5.2.7 on 2026-07-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0040_actionitem_deliverable_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemcomment',
            name='candidates_token_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionitemcomment',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Wall-clock time for the AI completion turn that produced this comment, if any.', null=True),
        ),
        migrations.AddField(
            model_name='actionitemcomment',
            name='prompt_token_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
