# Generated by Django 5.2.7 on 2026-07-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0041_actionitemcomment_candidates_token_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='assigned_agent_type',
            field=models.CharField(blank=True, choices=[('gtm_strategist', 'Charlie · GTM Strategist'), ('portfolio', 'Nora · Portfolio Agent'), ('resource', 'Theo · Resource Agent'), ('insights', 'Milo · Insights Agent')], help_text='Which AI agent (if any) this task has been routed to for autonomous completion.', max_length=20, null=True),
        ),
    ]
