# Generated by Django 5.2.7 on 2026-07-16 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0042_actionitem_assigned_agent_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='crm_sync_status',
            field=models.CharField(choices=[('not_synced', 'Not Synced'), ('synced', 'Synced'), ('error', 'Error')], default='not_synced', max_length=20),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='crm_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='external_crm_task_id',
            field=models.CharField(blank=True, default='', help_text='ID of the corresponding task in the connected CRM (e.g. HubSpot), if pushed there.', max_length=64),
        ),
        migrations.CreateModel(
            name='WorkspaceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('hubspot', 'HubSpot (CRM)')], max_length=20)),
                ('auth_method', models.CharField(choices=[('api_key', 'API Key / Token'), ('oauth', 'OAuth')], default='api_key', max_length=20)),
                ('encrypted_credentials', models.TextField(blank=True, default='')),
                ('token_preview', models.CharField(blank=True, default='', help_text='Last 4 chars, for display only', max_length=8)),
                ('status', models.CharField(choices=[('not_connected', 'Not Connected'), ('connected', 'Connected'), ('error', 'Error')], default='not_connected', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_integrations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='gtm.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'provider')},
            },
        ),
    ]
