# Generated by Django 5.2.7 on 2026-07-17 07:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0043_actionitem_crm_sync_status_actionitem_crm_synced_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydocument',
            name='analysis_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('complete', 'Analysis Complete'), ('failed', 'Analysis Failed'), ('no_credits', 'AI Credits Exhausted')], default='uploaded', max_length=12),
        ),
        migrations.AlterField(
            model_name='deliverydocument',
            name='analysis_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('complete', 'Analysis Complete'), ('failed', 'Analysis Failed'), ('no_credits', 'AI Credits Exhausted')], default='uploaded', max_length=12),
        ),
        migrations.AlterField(
            model_name='gtmfile',
            name='audit_status',
            field=models.CharField(choices=[('none', 'Not Audited'), ('pending', 'Awaiting Audit'), ('auditing', 'Auditing…'), ('complete', 'Audit Complete'), ('failed', 'Audit Failed'), ('no_credits', 'AI Credits Exhausted')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='response',
            name='ai_insight_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed'), ('no_credits', 'AI Credits Exhausted')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='resultsnapshot',
            name='ai_playbook_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed'), ('no_credits', 'AI Credits Exhausted')], db_index=True, default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='AICreditAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_length', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('token_budget', models.PositiveIntegerField(default=500000, help_text='Total Gemini prompt+output tokens allowed per period.')),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('period_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_account', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_account', to='gtm.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AICreditTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('playbook', 'Playbook generation'), ('diagnostic', 'Diagnostic insight'), ('diagnostic_batch', 'Diagnostic insight (batch)'), ('enrichment', 'Financial/competitor enrichment'), ('extract_tasks', 'Task extraction from playbook'), ('context_note_rewrite', 'Context note rewrite'), ('chat', 'GTM Strategist chat'), ('workspace_agent', 'Workspace agent chat'), ('team_chat', 'Team chat'), ('action_item_completion', 'Action item completion'), ('evidence_audit', 'Strategic evidence audit'), ('resource_audit', 'Resource library audit'), ('category_analysis', 'Category document analysis'), ('delivery_analysis', 'Delivery document analysis'), ('document_ocr', 'Attachment OCR/text extraction'), ('gap_suggestions', 'Gap analysis suggestions'), ('gap_action_items', 'Gap-to-action-item breakdown'), ('client_summary', 'Client summary draft')], max_length=32)),
                ('tokens_spent', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gtm.aicreditaccount')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_credit_transactions', to='gtm.assessmentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aicreditaccount',
            index=models.Index(fields=['workspace'], name='gtm_aicredi_workspa_178edc_idx'),
        ),
        migrations.AddIndex(
            model_name='aicreditaccount',
            index=models.Index(fields=['user'], name='gtm_aicredi_user_id_a03241_idx'),
        ),
        migrations.AddConstraint(
            model_name='aicreditaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', True), ('workspace__isnull', False)), models.Q(('user__isnull', False), ('workspace__isnull', True)), _connector='OR'), name='ai_credit_account_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='aicredittransaction',
            index=models.Index(fields=['account', '-created_at'], name='gtm_aicredi_account_4b7403_idx'),
        ),
        migrations.AddIndex(
            model_name='aicredittransaction',
            index=models.Index(fields=['feature', '-created_at'], name='gtm_aicredi_feature_1e0d8c_idx'),
        ),
    ]
