# Generated by Django 5.2.7 on 2026-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0044_alter_categorydocument_analysis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='task_refs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workspacechatmessage',
            name='task_refs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
