# Generated by Django 5.2.7 on 2026-07-17 14:09

from django.conf import settings
from django.db import migrations, models


def _backfill_and_dedupe_action_items(apps, schema_editor):
    """Populate note_key for every existing row, then merge any pre-existing
    duplicates (same normalized note in the same session/workspace/creator
    scope) before the uniqueness constraints below get added -- otherwise
    the AddConstraint operations would fail on any duplicate that already
    exists. Keeps the oldest row per duplicate group and reassigns its
    comments rather than losing them."""
    ActionItem = apps.get_model('gtm', 'ActionItem')
    ActionItemComment = apps.get_model('gtm', 'ActionItemComment')

    items = list(ActionItem.objects.only(
        'id', 'note', 'note_key', 'session_id', 'workspace_id', 'created_by_id', 'created_at'
    ))

    groups = {}
    for item in items:
        item.note_key = (item.note or '').strip().lower()
        if item.session_id is not None:
            scope_key = ('session', item.session_id, item.note_key)
        elif item.workspace_id is not None:
            scope_key = ('workspace', item.workspace_id, item.note_key)
        else:
            scope_key = ('creator', item.created_by_id, item.note_key)
        groups.setdefault(scope_key, []).append(item)

    ActionItem.objects.bulk_update(items, ['note_key'], batch_size=500)

    for group_items in groups.values():
        if len(group_items) < 2:
            continue
        group_items.sort(key=lambda i: (i.created_at, i.id))
        keeper, *extras = group_items
        extra_ids = [extra.id for extra in extras]
        ActionItemComment.objects.filter(action_item_id__in=extra_ids).update(action_item_id=keeper.id)
        ActionItem.objects.filter(id__in=extra_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0045_chatmessage_task_refs_workspacechatmessage_task_refs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='note_key',
            field=models.CharField(blank=True, default='', editable=False, help_text='Normalized (trimmed, lowercased) note text, used to enforce no-duplicate-tasks constraints.', max_length=240),
        ),
        migrations.RunPython(_backfill_and_dedupe_action_items, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='actionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('session', 'note_key'), name='unique_actionitem_note_per_session'),
        ),
        migrations.AddConstraint(
            model_name='actionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', True), ('workspace__isnull', False)), fields=('workspace', 'note_key'), name='unique_actionitem_note_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='actionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', True), ('workspace__isnull', True)), fields=('created_by', 'note_key'), name='unique_actionitem_note_per_creator_unscoped'),
        ),
    ]
