# Generated by Django 5.2.7 on 2026-07-17 14:57

import django.db.models.deletion
from django.db import migrations, models


def _backfill_gap_metric_links(apps, schema_editor):
    """Before this migration, the only record of which gap a task was created
    for was the write-only metadata on the 'task_created' activity event
    logged by generate_action_items_for_gap. Read those breadcrumbs back to
    link pre-existing tasks to their gap metric."""
    ActionItem = apps.get_model('gtm', 'ActionItem')
    GapAnalysisMetric = apps.get_model('dashboard', 'GapAnalysisMetric')
    WorkspaceActivityEvent = apps.get_model('gtm', 'WorkspaceActivityEvent')

    valid_metric_ids = set(GapAnalysisMetric.objects.values_list('id', flat=True))

    events = WorkspaceActivityEvent.objects.filter(
        event_type='task_created',
        object_type='action_item',
    ).exclude(object_id='').values_list('object_id', 'metadata')

    for object_id, metadata in events:
        if not isinstance(metadata, dict) or metadata.get('source') != 'gap_remediation':
            continue
        gap_metric_id = metadata.get('gap_metric_id')
        if gap_metric_id not in valid_metric_ids:
            continue
        try:
            item_id = int(object_id)
        except (TypeError, ValueError):
            continue
        ActionItem.objects.filter(id=item_id, gap_metric__isnull=True).update(gap_metric_id=gap_metric_id)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_gap_metric_lifecycle'),
        ('gtm', '0046_actionitem_note_key_dedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='gap_metric',
            field=models.ForeignKey(blank=True, help_text='The gap this task was generated to help close, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='dashboard.gapanalysismetric'),
        ),
        migrations.RunPython(_backfill_gap_metric_links, reverse_code=migrations.RunPython.noop),
    ]
