# Generated by Django 5.2.7 on 2026-07-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0047_gap_metric_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='document_refs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workspacechatmessage',
            name='document_refs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
