# Generated by Django 5.2.7 on 2026-07-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0048_chatmessage_document_refs_workspacechatmessage_document_refs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLock',
            fields=[
                ('lock_key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
