# Generated by Django 5.2.7 on 2026-07-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0049_aigenerationlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsnapshot',
            name='ai_risk_status',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='', max_length=20),
        ),
    ]
