# Generated by Django 5.2.7 on 2026-07-21 10:44

import django.db.models.deletion
import gtm.models_beta
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0050_alter_resultsnapshot_ai_risk_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=gtm.models_beta._generate_code, max_length=16, unique=True)),
                ('email', models.EmailField(blank=True, default='', help_text="Who this code was generated for -- used as the send target for the 'Email invite code' admin action. Not enforced at signup: the code itself is the gate, not a match against this address.", max_length=254)),
                ('note', models.CharField(blank=True, default='', help_text='e.g. "Jane @ Acme"', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Blank = never expires.', null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_codes_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_code_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
