# Generated by Django 5.2.7 on 2026-08-08 12:09

from django.db import migrations, models
from django.utils import timezone

# Recalibration constants -- hardcoded (not imported from the model) so this
# migration stays stable if the model constants change later. Matches
# AICreditAccount.TIER_MONTHLY_TOKEN_BUDGET[free] / DEFAULT_PERSONAL_TOKEN_BUDGET.
FREE_WORKSPACE_BUDGET = 250_000
FREE_PERSONAL_BUDGET = 100_000


def normalize_existing_accounts(apps, schema_editor):
    """Move every existing account onto the recalibrated free monthly tier.

    Before this change budgets were a flat 500K/day (workspace) or 100K/day
    (personal). We're deliberately recalibrating to a monthly cadence with a
    smaller free allowance, so stale daily accounts are reset to a fresh
    monthly period. Admins can re-grant specific accounts to Pro/Scale after.
    """
    AICreditAccount = apps.get_model('gtm', 'AICreditAccount')
    now = timezone.now()
    for account in AICreditAccount.objects.all().iterator():
        account.tier = 'free'
        account.period_length = 'monthly'
        account.token_budget = FREE_WORKSPACE_BUDGET if account.workspace_id else FREE_PERSONAL_BUDGET
        account.tokens_used = 0
        account.period_started_at = now
        account.save(update_fields=[
            'tier', 'period_length', 'token_budget', 'tokens_used', 'period_started_at',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0051_betainvitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicreditaccount',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('scale', 'Scale')], default='free', help_text='Pricing tier. Seeds token_budget on creation; change it to re-grant a preset budget.', max_length=16),
        ),
        migrations.AlterField(
            model_name='aicreditaccount',
            name='period_length',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='aicreditaccount',
            name='token_budget',
            field=models.PositiveIntegerField(default=250000, help_text='Total Gemini prompt+output tokens allowed per period. Source of truth for enforcement; can be overridden independently of the tier.'),
        ),
        migrations.RunPython(normalize_existing_accounts, migrations.RunPython.noop),
    ]
