# Generated by Django 5.2.7 on 2026-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm', '0052_aicreditaccount_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betainvitecode',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the invite email was last sent to the address above. Blank = never sent. Doubles as the send-once latch: saving a code in the admin only auto-sends while this is blank (or when `email` changes).', null=True),
        ),
    ]
