# Generated by Django 5.2.7 on 2025-12-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelanalytics',
            old_name='percent_of_revenue',
            new_name='revenue',
        ),
    ]
