# Generated by Django 5.2.7 on 2025-12-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_percent_of_revenue_channelanalytics_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapAnalysisMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Lead Generation', 'Lead Generation'), ('Sales Efficiency', 'Sales Efficiency'), ('Customer Success', 'Customer Success'), ('Product Marketing', 'Product Marketing'), ('Sales Velocity', 'Sales Velocity'), ('Marketing ROI', 'Marketing ROI')], max_length=100)),
                ('metric', models.CharField(max_length=100, unique=True)),
                ('target', models.FloatField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('recommendation', models.TextField()),
            ],
        ),
    ]
