# Generated by Django 5.2.7 on 2025-12-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_gapanalysismetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanalysismetric',
            name='current',
            field=models.FloatField(default=0),
        ),
    ]
