# Generated by Django 5.2.7 on 2026-02-10 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_gapanalysismetric_current'),
        ('gtm', '0017_actionitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanalysismetric',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gap_metrics', to='gtm.assessmentsession'),
        ),
        migrations.AddField(
            model_name='gapanalysismetric',
            name='source',
            field=models.CharField(choices=[('AI', 'AI'), ('USER', 'User')], default='USER', max_length=4),
        ),
        migrations.AlterField(
            model_name='gapanalysismetric',
            name='metric',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='gapanalysismetric',
            unique_together={('metric', 'session')},
        ),
    ]
