# Generated by Django 5.2.7 on 2026-02-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_gapanalysismetric_session_gapanalysismetric_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelanalytics',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='channelanalytics',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gapanalysismetric',
            name='metric',
            field=models.CharField(choices=[('Monthly Qualified Leads', 'Monthly Qualified Leads'), ('Average Deal Size', 'Average Deal Size'), ('Net Revenue Retention', 'Net Revenue Retention'), ('Product Qualified Leads', 'Product Qualified Leads'), ('Win Rate', 'Win Rate'), ('CAC Payback Period', 'CAC Payback Period')], max_length=100),
        ),
    ]
