# Generated by Django 5.2.7 on 2026-02-11 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_channelanalytics_change_and_more'),
        ('gtm', '0018_actionitem_assigned_to_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gapanalysismetric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gapanalysismetric',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gap_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gapanalysismetric',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gap_metrics', to='gtm.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='gapanalysismetric',
            unique_together={('metric', 'session', 'workspace')},
        ),
    ]
