# Generated by Django 5.2.7 on 2026-03-11 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_gapanalysismetric_unique_together_and_more'),
        ('gtm', '0019_actionitem_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('file', 'File Upload'), ('link', 'External Link')], default='link', max_length=10)),
                ('category', models.CharField(choices=[('strategy', 'Strategy & Planning'), ('sales', 'Sales Enablement'), ('marketing', 'Marketing Assets'), ('product', 'Product & Tech'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='workspace_resources/%Y/%m/')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='gtm.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
