# Generated by Django 5.2.7 on 2026-03-21 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_dedupe_gap_metrics'),
        ('gtm', '0027_actionitem_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResourceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.CharField(help_text='Short explanation of why this resource was recommended by AI', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='dashboard.resource')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_resource_matches', to='gtm.assessmentsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'resource')},
            },
        ),
    ]
