# Generated by Django 5.2.7 on 2026-04-05 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_airesourcerecommendation'),
        ('gtm', '0028_gtmfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('success', 'Success'), ('info', 'Information'), ('warning', 'Warning'), ('danger', 'Urgent')], default='info', max_length=10)),
                ('notification_type', models.CharField(choices=[('task', 'Task Assignment'), ('task_status', 'Task Status Update'), ('invite', 'Workspace Invitation'), ('ai_report', 'AI Report Ready'), ('system', 'System Message')], default='system', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gtm.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='dashboard_n_recipie_91720a_idx'), models.Index(fields=['workspace', 'is_read'], name='dashboard_n_workspa_f73e19_idx')],
            },
        ),
    ]
