# Generated by Django 5.2.7 on 2026-04-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='ai_audit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='ai_audit_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='ai_score_modifier',
            field=models.IntegerField(default=0, help_text='Advisory score impact (−5 to +5) suggested by the AI auditor.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='audit_status',
            field=models.CharField(choices=[('none', 'Not Audited'), ('pending', 'Awaiting Audit'), ('auditing', 'Auditing…'), ('complete', 'Audit Complete'), ('failed', 'Audit Failed')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='gtm_categories',
            field=models.JSONField(blank=True, default=list, help_text='List of GTM categories this asset most impacts.'),
        ),
    ]
