# Generated by Django 5.2.7 on 2026-06-02 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_resource_ai_audit_at_resource_ai_audit_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_task_assigned', models.BooleanField(default=True)),
                ('email_task_completed', models.BooleanField(default=True)),
                ('email_workspace_invite', models.BooleanField(default=True)),
                ('email_ai_insights', models.BooleanField(default=False)),
                ('inapp_task_assigned', models.BooleanField(default=True)),
                ('inapp_task_completed', models.BooleanField(default=True)),
                ('inapp_workspace_activity', models.BooleanField(default=True)),
                ('inapp_ai_insights', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
