# Generated by Django 5.2.7 on 2026-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='audit_status',
            field=models.CharField(choices=[('none', 'Not Audited'), ('pending', 'Awaiting Audit'), ('auditing', 'Auditing…'), ('complete', 'Audit Complete'), ('failed', 'Audit Failed'), ('no_credits', 'AI Credits Exhausted')], default='none', max_length=10),
        ),
    ]
