# Generated by Django 5.2.7 on 2026-07-17 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_resource_audit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanalysismetric',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gapanalysismetric',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('target_reached', 'Target reached'), ('manual', 'Manually resolved')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='gapanalysismetric',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='GapMetricMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('source', models.CharField(choices=[('manual', 'Manual check-in'), ('crm', 'CRM')], default='manual', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('gap_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dashboard.gapanalysismetric')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
    ]
