# Generated by Django 5.2.7 on 2026-07-18 06:14

from django.db import migrations, models


def _backfill_estimate_method(apps, schema_editor):
    """Best-effort backfill for rows that predate this field. Reliable
    signal first: a metric closed because a real measurement hit target
    could only have gotten there via the measured check-in flow. For
    everything else we only have the coarse AI/USER 'source' field, so this
    is a labeled assumption (existing AI rows are assumed to be real Gemini
    output) rather than a recovered fact -- true generator history wasn't
    retained for rows created before this migration."""
    GapAnalysisMetric = apps.get_model('dashboard', 'GapAnalysisMetric')

    GapAnalysisMetric.objects.filter(closed_reason='target_reached').update(estimate_method='measured')
    GapAnalysisMetric.objects.filter(estimate_method='', source='USER').update(estimate_method='manual_entry')
    GapAnalysisMetric.objects.filter(estimate_method='', source='AI').update(estimate_method='gemini')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_gap_metric_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanalysismetric',
            name='estimate_method',
            field=models.CharField(blank=True, choices=[('gemini', 'AI Estimate'), ('formula', 'Formula Estimate'), ('manual_entry', 'Manual Entry'), ('measured', 'Measured')], default='', help_text='Where the current value actually came from -- an AI guess, a deterministic fallback formula, a manually typed number, or a real measured check-in.', max_length=20),
        ),
        migrations.RunPython(_backfill_estimate_method, reverse_code=migrations.RunPython.noop),
    ]
