# Generated by Django 5.2.7 on 2026-07-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_gap_metric_estimate_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gapmetricmeasurement',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual check-in'), ('crm', 'CRM'), ('agent', 'AI agent (chat-relayed)')], default='manual', max_length=10),
        ),
    ]
