# Generated by Django 5.2.7 on 2026-08-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_betafeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='betafeedback',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='Triage flag for beta ops -- set once someone has read/actioned this.'),
        ),
    ]
