# Generated by Django 5.2.7 on 2026-08-07 11:46

from django.db import migrations, models


def turn_on_ai_insight_emails(apps, schema_editor):
    """email_ai_insights used to default False, so existing rows have it off.
    The product decision is now email-for-everything, so switch existing
    users on too (new rows already get True from the model default)."""
    UserSettings = apps.get_model('dashboard', 'UserSettings')
    UserSettings.objects.filter(email_ai_insights=False).update(email_ai_insights=True)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_betafeedback_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='email_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='email_ai_insights',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(turn_on_ai_insight_emails, migrations.RunPython.noop),
    ]
